import { Listing } from '@/types'

export const listings: Listing[] = [
  // Sports
  {
    id: 'list-1',
    providerId: 'prov-1',
    categoryId: 'cat-kids-sports',
    title: 'Kids Mountain Biking Course',
    titleHe: 'קורס אופני הרים לילדים',
    description: 'Learn to ride mountain bikes safely on trails around Beit Shemesh. Small groups, professional instruction, all equipment provided. Build confidence and enjoy nature!',
    descriptionHe: 'למדו לרכוב על אופני הרים בבטחה בשבילים סביב בית שמש. קבוצות קטנות, הדרכה מקצועית, כל הציוד מסופק. בנו ביטחון ותיהנו מהטבע!',
    price: 180,
    priceType: 'PER_SESSION',
    currency: 'ILS',
    duration: 90,
    ageMin: 8,
    ageMax: 14,
    gender: 'ALL',
    instructorGender: 'MALE',
    language: ['he', 'en'],
    maxParticipants: 8,
    location: 'Meeting point: Nachal Dolev Park',
    neighborhood: 'רמת בית שמש א',
    isOnline: false,
    schedule: {
      sunday: [{ start: '16:00', end: '17:30' }],
      tuesday: [{ start: '16:00', end: '17:30' }],
      thursday: [{ start: '16:00', end: '17:30' }],
    },
    subsidies: ['מאוחדת'],
    status: 'ACTIVE',
    isFeatured: true,
    viewCount: 234,
    createdAt: new Date('2024-09-01'),
    updatedAt: new Date('2024-12-01'),
    images: [
      { id: 'img-l1-1', url: 'https://images.unsplash.com/photo-1541625602330-2277a4c46182?w=800', alt: 'Mountain biking', order: 0 },
      { id: 'img-l1-2', url: 'https://images.unsplash.com/photo-1544191696-102dbdaeeaa0?w=800', alt: 'Kids biking', order: 1 },
    ],
  },
  {
    id: 'list-2',
    providerId: 'prov-3',
    categoryId: 'cat-kids-sports',
    title: 'Soccer Training - Ages 6-10',
    titleHe: 'אימון כדורגל - גילאי 6-10',
    description: 'Professional soccer training for young players. Learn fundamentals, teamwork, and game skills. Weekly matches and tournaments.',
    descriptionHe: 'אימון כדורגל מקצועי לשחקנים צעירים. למדו יסודות, עבודת צוות ומיומנויות משחק. משחקים ותחרויות שבועיות.',
    price: 250,
    priceType: 'MONTHLY',
    currency: 'ILS',
    duration: 60,
    ageMin: 6,
    ageMax: 10,
    gender: 'MALE',
    instructorGender: 'MALE',
    language: ['he'],
    maxParticipants: 16,
    location: 'מגרש הכדורגל העירוני',
    neighborhood: 'בית שמש הותיקה',
    isOnline: false,
    schedule: {
      monday: [{ start: '16:30', end: '17:30' }],
      wednesday: [{ start: '16:30', end: '17:30' }],
    },
    subsidies: [],
    status: 'ACTIVE',
    isFeatured: true,
    viewCount: 456,
    createdAt: new Date('2024-08-15'),
    updatedAt: new Date('2024-11-20'),
    images: [
      { id: 'img-l2-1', url: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800', alt: 'Soccer', order: 0 },
    ],
  },
  {
    id: 'list-3',
    providerId: 'prov-3',
    categoryId: 'cat-kids-sports',
    title: 'Soccer Training - Ages 11-16',
    titleHe: 'אימון כדורגל - גילאי 11-16',
    description: 'Advanced soccer training for teenage players. Focus on tactics, fitness, and competitive play.',
    descriptionHe: 'אימון כדורגל מתקדם לשחקנים מתבגרים. דגש על טקטיקה, כושר גופני ומשחק תחרותי.',
    price: 300,
    priceType: 'MONTHLY',
    currency: 'ILS',
    duration: 90,
    ageMin: 11,
    ageMax: 16,
    gender: 'MALE',
    instructorGender: 'MALE',
    language: ['he'],
    maxParticipants: 20,
    location: 'מגרש הכדורגל העירוני',
    neighborhood: 'בית שמש הותיקה',
    isOnline: false,
    schedule: {
      sunday: [{ start: '17:00', end: '18:30' }],
      tuesday: [{ start: '17:00', end: '18:30' }],
      thursday: [{ start: '17:00', end: '18:30' }],
    },
    subsidies: [],
    status: 'ACTIVE',
    isFeatured: false,
    viewCount: 321,
    createdAt: new Date('2024-08-15'),
    updatedAt: new Date('2024-11-20'),
    images: [
      { id: 'img-l3-1', url: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800', alt: 'Soccer teens', order: 0 },
    ],
  },
  // Dance
  {
    id: 'list-4',
    providerId: 'prov-2',
    categoryId: 'cat-kids-dance',
    title: 'Ballet for Girls - Beginners',
    titleHe: 'בלט לבנות - מתחילות',
    description: 'Introduction to classical ballet for young girls. Learn basic positions, movements, and develop grace and coordination.',
    descriptionHe: 'מבוא לבלט קלאסי לבנות צעירות. למדו תנוחות בסיסיות, תנועות ופתחו חן וקואורדינציה.',
    price: 220,
    priceType: 'MONTHLY',
    currency: 'ILS',
    duration: 45,
    ageMin: 4,
    ageMax: 7,
    gender: 'FEMALE',
    instructorGender: 'FEMALE',
    language: ['he'],
    maxParticipants: 12,
    location: 'מרכז מסחרי רסקו, רמב״ש ב׳',
    neighborhood: 'רמת בית שמש ב',
    isOnline: false,
    schedule: {
      sunday: [{ start: '15:00', end: '15:45' }],
      wednesday: [{ start: '15:00', end: '15:45' }],
    },
    subsidies: [],
    status: 'ACTIVE',
    isFeatured: true,
    viewCount: 567,
    createdAt: new Date('2024-07-01'),
    updatedAt: new Date('2024-12-01'),
    images: [
      { id: 'img-l4-1', url: 'https://images.unsplash.com/photo-1518834107812-67b0b7c58434?w=800', alt: 'Ballet class', order: 0 },
    ],
  },
  {
    id: 'list-5',
    providerId: 'prov-2',
    categoryId: 'cat-kids-dance',
    title: 'Jazz Dance - Ages 8-12',
    titleHe: 'ריקודי ג׳אז - גילאי 8-12',
    description: 'Fun and energetic jazz dance classes. Learn choreography, improve flexibility, and perform in our annual recital.',
    descriptionHe: 'שיעורי ריקוד ג׳אז כיפיים ואנרגטיים. למדו כוריאוגרפיה, שפרו גמישות והופיעו במופע השנתי שלנו.',
    price: 240,
    priceType: 'MONTHLY',
    currency: 'ILS',
    duration: 60,
    ageMin: 8,
    ageMax: 12,
    gender: 'FEMALE',
    instructorGender: 'FEMALE',
    language: ['he'],
    maxParticipants: 15,
    location: 'מרכז מסחרי רסקו, רמב״ש ב׳',
    neighborhood: 'רמת בית שמש ב',
    isOnline: false,
    schedule: {
      monday: [{ start: '16:00', end: '17:00' }],
      thursday: [{ start: '16:00', end: '17:00' }],
    },
    subsidies: [],
    status: 'ACTIVE',
    isFeatured: false,
    viewCount: 234,
    createdAt: new Date('2024-07-01'),
    updatedAt: new Date('2024-11-15'),
    images: [
      { id: 'img-l5-1', url: 'https://images.unsplash.com/photo-1508700929628-666bc8bd84ea?w=800', alt: 'Jazz dance', order: 0 },
    ],
  },
  // Music
  {
    id: 'list-6',
    providerId: 'prov-4',
    categoryId: 'cat-kids-music',
    title: 'Piano Lessons - Private',
    titleHe: 'שיעורי פסנתר - פרטי',
    description: 'Private piano lessons for all levels. Classical and modern repertoire. Preparation for exams available.',
    descriptionHe: 'שיעורי פסנתר פרטיים לכל הרמות. רפרטואר קלאסי ומודרני. הכנה לבחינות אפשרית.',
    price: 150,
    priceType: 'PER_SESSION',
    currency: 'ILS',
    duration: 45,
    ageMin: 6,
    ageMax: 18,
    gender: 'ALL',
    instructorGender: 'FEMALE',
    language: ['he', 'en'],
    maxParticipants: 1,
    location: 'רחוב הרב קוק 22, רמב״ש א׳',
    neighborhood: 'רמת בית שמש א',
    isOnline: false,
    schedule: {
      sunday: [
        { start: '14:00', end: '14:45' },
        { start: '15:00', end: '15:45' },
        { start: '16:00', end: '16:45' },
      ],
      monday: [
        { start: '14:00', end: '14:45' },
        { start: '15:00', end: '15:45' },
      ],
      tuesday: [
        { start: '14:00', end: '14:45' },
        { start: '15:00', end: '15:45' },
        { start: '16:00', end: '16:45' },
      ],
      wednesday: [
        { start: '14:00', end: '14:45' },
        { start: '15:00', end: '15:45' },
      ],
      thursday: [
        { start: '14:00', end: '14:45' },
        { start: '15:00', end: '15:45' },
      ],
    },
    subsidies: [],
    status: 'ACTIVE',
    isFeatured: false,
    viewCount: 189,
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2024-11-01'),
    images: [
      { id: 'img-l6-1', url: 'https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?w=800', alt: 'Piano lessons', order: 0 },
    ],
  },
  {
    id: 'list-7',
    providerId: 'prov-4',
    categoryId: 'cat-kids-music',
    title: 'Guitar Lessons - All Levels',
    titleHe: 'שיעורי גיטרה - כל הרמות',
    description: 'Learn acoustic or electric guitar. Rock, pop, classical styles. Fun and engaging lessons.',
    descriptionHe: 'למדו גיטרה אקוסטית או חשמלית. סגנונות רוק, פופ, קלאסי. שיעורים כיפיים ומרתקים.',
    price: 140,
    priceType: 'PER_SESSION',
    currency: 'ILS',
    duration: 45,
    ageMin: 8,
    ageMax: 18,
    gender: 'ALL',
    instructorGender: 'MALE',
    language: ['he'],
    maxParticipants: 1,
    location: 'רחוב הרב קוק 22, רמב״ש א׳',
    neighborhood: 'רמת בית שמש א',
    isOnline: false,
    subsidies: [],
    status: 'ACTIVE',
    isFeatured: false,
    viewCount: 145,
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2024-10-15'),
    images: [
      { id: 'img-l7-1', url: 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=800', alt: 'Guitar lessons', order: 0 },
    ],
  },
  // Art
  {
    id: 'list-8',
    providerId: 'prov-5',
    categoryId: 'cat-kids-art',
    title: 'Art Club - Mixed Media',
    titleHe: 'חוג אמנות - מדיה מעורבת',
    description: 'Explore different art techniques: painting, collage, sculpture, and more. Express creativity in a supportive environment.',
    descriptionHe: 'חקרו טכניקות אמנות שונות: ציור, קולאז\', פיסול ועוד. הביעו יצירתיות בסביבה תומכת.',
    price: 180,
    priceType: 'MONTHLY',
    currency: 'ILS',
    duration: 60,
    ageMin: 6,
    ageMax: 12,
    gender: 'ALL',
    instructorGender: 'FEMALE',
    language: ['he'],
    maxParticipants: 10,
    location: 'רחוב דוד המלך 8, רמב״ש ג׳',
    neighborhood: 'רמת בית שמש ג',
    isOnline: false,
    schedule: {
      tuesday: [{ start: '16:00', end: '17:00' }],
    },
    subsidies: [],
    status: 'ACTIVE',
    isFeatured: false,
    viewCount: 98,
    createdAt: new Date('2024-09-01'),
    updatedAt: new Date('2024-11-01'),
    images: [
      { id: 'img-l8-1', url: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800', alt: 'Art class', order: 0 },
    ],
  },
  // Tutoring
  {
    id: 'list-9',
    providerId: 'prov-6',
    categoryId: 'cat-kids-tutoring',
    title: 'SAT Prep Course',
    titleHe: 'קורס הכנה ל-SAT',
    description: 'Comprehensive SAT preparation. Covers all sections, practice tests, and test-taking strategies. Small groups.',
    descriptionHe: 'הכנה מקיפה ל-SAT. מכסה את כל החלקים, מבחני תרגול ואסטרטגיות מבחן. קבוצות קטנות.',
    price: 3500,
    priceType: 'FIXED',
    currency: 'ILS',
    duration: 120,
    ageMin: 15,
    ageMax: 18,
    gender: 'ALL',
    instructorGender: 'FEMALE',
    language: ['en'],
    maxParticipants: 6,
    location: 'רחוב האלון 45, רמב״ש א׳',
    neighborhood: 'רמת בית שמש א',
    isOnline: false,
    schedule: {
      sunday: [{ start: '18:00', end: '20:00' }],
      wednesday: [{ start: '18:00', end: '20:00' }],
    },
    subsidies: [],
    status: 'ACTIVE',
    isFeatured: true,
    viewCount: 287,
    createdAt: new Date('2024-08-01'),
    updatedAt: new Date('2024-12-01'),
    images: [
      { id: 'img-l9-1', url: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800', alt: 'SAT prep', order: 0 },
    ],
  },
  {
    id: 'list-10',
    providerId: 'prov-14',
    categoryId: 'cat-kids-tutoring',
    title: 'Math Tutoring - High School',
    titleHe: 'שיעורים פרטיים במתמטיקה - תיכון',
    description: 'Private math tutoring for high school students. Bagrut preparation 3-5 units. Patient and effective teaching.',
    descriptionHe: 'שיעורים פרטיים במתמטיקה לתלמידי תיכון. הכנה לבגרות 3-5 יחידות. הוראה סבלנית ויעילה.',
    price: 120,
    priceType: 'HOURLY',
    currency: 'ILS',
    duration: 60,
    ageMin: 14,
    ageMax: 18,
    gender: 'ALL',
    instructorGender: 'FEMALE',
    language: ['he'],
    maxParticipants: 1,
    location: 'רחוב האגוז 18, רמב״ש ג׳',
    neighborhood: 'רמת בית שמש ג',
    isOnline: true,
    subsidies: [],
    status: 'ACTIVE',
    isFeatured: false,
    viewCount: 156,
    createdAt: new Date('2024-10-01'),
    updatedAt: new Date('2024-11-20'),
    images: [
      { id: 'img-l10-1', url: 'https://images.unsplash.com/photo-1596495578065-6e0763fa1178?w=800', alt: 'Math tutoring', order: 0 },
    ],
  },
  // Swimming
  {
    id: 'list-11',
    providerId: 'prov-13',
    categoryId: 'cat-kids-sports',
    title: 'Swimming Lessons - Girls',
    titleHe: 'שיעורי שחייה - בנות',
    description: 'Swimming lessons for girls in a comfortable environment. All levels from beginners to advanced. Heated pool.',
    descriptionHe: 'שיעורי שחייה לבנות בסביבה נוחה. כל הרמות ממתחילות ועד מתקדמות. בריכה מחוממת.',
    price: 200,
    priceType: 'MONTHLY',
    currency: 'ILS',
    duration: 45,
    ageMin: 5,
    ageMax: 14,
    gender: 'FEMALE',
    instructorGender: 'FEMALE',
    language: ['he', 'en'],
    maxParticipants: 8,
    location: 'בריכת מרכז הספורט, רמב״ש א׳',
    neighborhood: 'רמת בית שמש א',
    isOnline: false,
    schedule: {
      sunday: [{ start: '15:00', end: '15:45' }, { start: '16:00', end: '16:45' }],
      tuesday: [{ start: '15:00', end: '15:45' }, { start: '16:00', end: '16:45' }],
      thursday: [{ start: '15:00', end: '15:45' }],
    },
    subsidies: ['מאוחדת', 'כללית'],
    status: 'ACTIVE',
    isFeatured: true,
    viewCount: 423,
    createdAt: new Date('2024-06-15'),
    updatedAt: new Date('2024-12-01'),
    images: [
      { id: 'img-l11-1', url: 'https://images.unsplash.com/photo-1530549387789-4c1017266635?w=800', alt: 'Swimming lessons', order: 0 },
    ],
  },
  // Camps
  {
    id: 'list-12',
    providerId: 'prov-15',
    categoryId: 'cat-kids-camps',
    title: 'Summer Camp 2025',
    titleHe: 'קייטנת קיץ 2025',
    description: 'Full-day summer camp with activities, sports, arts & crafts, trips, and more. Kosher meals included.',
    descriptionHe: 'קייטנת קיץ יום מלא עם פעילויות, ספורט, יצירה, טיולים ועוד. ארוחות כשרות כלולות.',
    price: 2800,
    priceType: 'FIXED',
    currency: 'ILS',
    duration: 480,
    ageMin: 4,
    ageMax: 10,
    gender: 'ALL',
    instructorGender: 'FEMALE',
    language: ['he'],
    maxParticipants: 40,
    location: 'בית הספר ממלכתי, רמב״ש א׳',
    neighborhood: 'רמת בית שמש א',
    isOnline: false,
    subsidies: [],
    status: 'ACTIVE',
    isFeatured: true,
    viewCount: 678,
    createdAt: new Date('2024-11-01'),
    updatedAt: new Date('2024-12-01'),
    images: [
      { id: 'img-l12-1', url: 'https://images.unsplash.com/photo-1596464716127-f2a82984de30?w=800', alt: 'Summer camp', order: 0 },
    ],
  },
  // Health & Wellness
  {
    id: 'list-13',
    providerId: 'prov-9',
    categoryId: 'cat-health',
    title: 'Morning Yoga - Women',
    titleHe: 'יוגה בוקר - נשים',
    description: 'Start your day with energizing yoga. Suitable for all levels. Bring your own mat.',
    descriptionHe: 'התחילו את היום עם יוגה מאזנת. מתאים לכל הרמות. יש להביא מזרון.',
    price: 50,
    priceType: 'PER_SESSION',
    currency: 'ILS',
    duration: 60,
    gender: 'FEMALE',
    instructorGender: 'FEMALE',
    language: ['he'],
    maxParticipants: 15,
    location: 'מרכז ספורט רמב״ש ב׳',
    neighborhood: 'רמת בית שמש ב',
    isOnline: false,
    schedule: {
      sunday: [{ start: '09:00', end: '10:00' }],
      tuesday: [{ start: '09:00', end: '10:00' }],
      thursday: [{ start: '09:00', end: '10:00' }],
    },
    subsidies: ['מאוחדת'],
    status: 'ACTIVE',
    isFeatured: true,
    viewCount: 345,
    createdAt: new Date('2024-05-01'),
    updatedAt: new Date('2024-11-15'),
    images: [
      { id: 'img-l13-1', url: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800', alt: 'Yoga class', order: 0 },
    ],
  },
  {
    id: 'list-14',
    providerId: 'prov-8',
    categoryId: 'cat-health',
    title: 'Child Therapy - CBT',
    titleHe: 'טיפול לילדים - CBT',
    description: 'Cognitive behavioral therapy for children dealing with anxiety, behavioral issues, or emotional challenges.',
    descriptionHe: 'טיפול קוגניטיבי התנהגותי לילדים המתמודדים עם חרדה, בעיות התנהגות או אתגרים רגשיים.',
    price: 400,
    priceType: 'PER_SESSION',
    currency: 'ILS',
    duration: 50,
    ageMin: 6,
    ageMax: 16,
    gender: 'ALL',
    instructorGender: 'FEMALE',
    language: ['he', 'en'],
    maxParticipants: 1,
    location: 'רחוב הגפן 12, רמב״ש ב׳',
    neighborhood: 'רמת בית שמש ב',
    isOnline: true,
    subsidies: ['מאוחדת', 'כללית', 'מכבי'],
    status: 'ACTIVE',
    isFeatured: false,
    viewCount: 189,
    createdAt: new Date('2024-04-01'),
    updatedAt: new Date('2024-11-01'),
    images: [
      { id: 'img-l14-1', url: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=800', alt: 'Therapy', order: 0 },
    ],
  },
  // Simcha Services
  {
    id: 'list-15',
    providerId: 'prov-11',
    categoryId: 'cat-simcha',
    title: 'Wedding Photography Package',
    titleHe: 'חבילת צילום לחתונה',
    description: 'Complete wedding photography: preparation, ceremony, reception. Includes edited album and digital files.',
    descriptionHe: 'צילום חתונה מלא: הכנות, טקס, קבלת פנים. כולל אלבום ערוך וקבצים דיגיטליים.',
    price: 8000,
    priceType: 'FIXED',
    currency: 'ILS',
    gender: 'ALL',
    language: ['he', 'en'],
    location: 'כל האזור',
    isOnline: false,
    subsidies: [],
    status: 'ACTIVE',
    isFeatured: true,
    viewCount: 234,
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-11-01'),
    images: [
      { id: 'img-l15-1', url: 'https://images.unsplash.com/photo-1537633552985-df8429e8048b?w=800', alt: 'Wedding photography', order: 0 },
    ],
  },
  {
    id: 'list-16',
    providerId: 'prov-12',
    categoryId: 'cat-simcha',
    title: 'Shabbat Chatan Catering',
    titleHe: 'קייטרינג לשבת חתן',
    description: 'Full Shabbat catering: Friday night, Shabbat day meals, seuda shlishit. Mehadrin kosher.',
    descriptionHe: 'קייטרינג שבת מלא: סעודת ליל שבת, סעודות יום שבת, סעודה שלישית. כשר למהדרין.',
    price: 120,
    priceType: 'CONTACT',
    currency: 'ILS',
    gender: 'ALL',
    language: ['he'],
    location: 'משלוחים לכל האזור',
    isOnline: false,
    subsidies: [],
    status: 'ACTIVE',
    isFeatured: false,
    viewCount: 178,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-10-15'),
    images: [
      { id: 'img-l16-1', url: 'https://images.unsplash.com/photo-1555244162-803834f70033?w=800', alt: 'Catering', order: 0 },
    ],
  },
  // Home Services
  {
    id: 'list-17',
    providerId: 'prov-10',
    categoryId: 'cat-home',
    title: 'Electrical Services',
    titleHe: 'שירותי חשמל',
    description: 'Licensed electrician. Repairs, installations, panel upgrades. Fast and reliable service.',
    descriptionHe: 'חשמלאי מוסמך. תיקונים, התקנות, שדרוג לוחות. שירות מהיר ואמין.',
    price: 150,
    priceType: 'HOURLY',
    currency: 'ILS',
    gender: 'ALL',
    language: ['he'],
    location: 'כל רמת בית שמש',
    isOnline: false,
    subsidies: [],
    status: 'ACTIVE',
    isFeatured: false,
    viewCount: 267,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-11-01'),
    images: [
      { id: 'img-l17-1', url: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800', alt: 'Electrician', order: 0 },
    ],
  },
  // Food
  {
    id: 'list-18',
    providerId: 'prov-7',
    categoryId: 'cat-stores',
    title: 'Shalom Pizza - Delivery',
    titleHe: 'שלום פיצה - משלוחים',
    description: 'Mehadrin kosher pizzeria. Pizzas, pastas, salads, kids meals. Free delivery on orders over ₪80.',
    descriptionHe: 'פיצריה כשרה למהדרין. פיצות, פסטות, סלטים, מנות ילדים. משלוח חינם בהזמנות מעל ₪80.',
    price: 45,
    priceType: 'CONTACT',
    currency: 'ILS',
    gender: 'ALL',
    language: ['he'],
    location: 'רחוב נחל דולב 3, רמב״ש א׳',
    neighborhood: 'רמת בית שמש א',
    isOnline: false,
    subsidies: [],
    status: 'ACTIVE',
    isFeatured: true,
    viewCount: 890,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-12-01'),
    images: [
      { id: 'img-l18-1', url: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800', alt: 'Pizza', order: 0 },
    ],
  },
]

// Helper functions
export const getListingById = (id: string): Listing | undefined => {
  return listings.find((l) => l.id === id)
}

export const getListingsByCategory = (categoryId: string): Listing[] => {
  return listings.filter((l) => l.categoryId === categoryId && l.status === 'ACTIVE')
}

export const getListingsByProvider = (providerId: string): Listing[] => {
  return listings.filter((l) => l.providerId === providerId)
}

export const getFeaturedListings = (): Listing[] => {
  return listings.filter((l) => l.isFeatured && l.status === 'ACTIVE')
}

export const getPopularListings = (limit: number = 6): Listing[] => {
  return [...listings]
    .filter((l) => l.status === 'ACTIVE')
    .sort((a, b) => b.viewCount - a.viewCount)
    .slice(0, limit)
}

export const getNewListings = (limit: number = 6): Listing[] => {
  return [...listings]
    .filter((l) => l.status === 'ACTIVE')
    .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())
    .slice(0, limit)
}

export const searchListings = (query: string): Listing[] => {
  const searchLower = query.toLowerCase()
  return listings.filter(
    (l) =>
      l.status === 'ACTIVE' &&
      (l.title.toLowerCase().includes(searchLower) ||
        l.titleHe?.includes(query) ||
        l.description.toLowerCase().includes(searchLower) ||
        l.descriptionHe?.includes(query))
  )
}

export const filterListings = (filters: {
  categoryId?: string
  neighborhood?: string
  ageMin?: number
  ageMax?: number
  gender?: string
  language?: string
  priceMax?: number
}): Listing[] => {
  return listings.filter((l) => {
    if (l.status !== 'ACTIVE') return false
    if (filters.categoryId && l.categoryId !== filters.categoryId) return false
    if (filters.neighborhood && l.neighborhood !== filters.neighborhood) return false
    if (filters.ageMin && l.ageMax && l.ageMax < filters.ageMin) return false
    if (filters.ageMax && l.ageMin && l.ageMin > filters.ageMax) return false
    if (filters.gender && l.gender && l.gender !== 'ALL' && l.gender !== filters.gender) return false
    if (filters.language && !l.language.includes(filters.language)) return false
    if (filters.priceMax && l.price && l.price > filters.priceMax) return false
    return true
  })
}
