import { Provider } from '@/types'

export const providers: Provider[] = [
  {
    id: 'prov-1',
    userId: 'user-prov-1',
    businessName: 'Geerz Biking',
    description: 'Professional biking lessons and guided tours for kids and adults in the beautiful hills around Beit Shemesh. We offer group lessons, private instruction, and family biking adventures.',
    shortDescription: 'שיעורי אופניים מקצועיים לילדים ומבוגרים',
    phone: '052-123-4567',
    email: 'info@geerz.co.il',
    website: 'https://geerz.co.il',
    location: 'רחוב נחל לכיש 15, רמת בית שמש א׳',
    neighborhood: 'רמת בית שמש א',
    subscriptionTier: 'PREMIUM',
    isVerified: true,
    isActive: true,
    images: [
      { id: 'img-1', url: 'https://images.unsplash.com/photo-1541625602330-2277a4c46182?w=800', alt: 'Kids biking', order: 0 },
    ],
  },
  {
    id: 'prov-2',
    userId: 'user-prov-2',
    businessName: 'רוקדים מהלב',
    description: 'סטודיו לריקוד ותנועה לבנות. אנחנו מציעים שיעורי בלט, ג׳אז, היפ-הופ ומחול ישראלי. המורות שלנו מנוסות ומסורות לפיתוח כל תלמידה.',
    shortDescription: 'סטודיו לריקוד לבנות - בלט, ג׳אז, מחול',
    phone: '054-987-6543',
    email: 'dance@rokdim.co.il',
    location: 'מרכז מסחרי רסקו, רמת בית שמש ב׳',
    neighborhood: 'רמת בית שמש ב',
    subscriptionTier: 'STANDARD',
    isVerified: true,
    isActive: true,
    brandColor: '#E91E63',
    images: [
      { id: 'img-2', url: 'https://images.unsplash.com/photo-1518834107812-67b0b7c58434?w=800', alt: 'Dance studio', order: 0 },
    ],
  },
  {
    id: 'prov-3',
    userId: 'user-prov-3',
    businessName: 'Soccer Stars Academy',
    description: 'Professional soccer training for boys ages 5-16. Our coaches are licensed and experienced in youth development. We participate in local leagues and tournaments.',
    shortDescription: 'אקדמיית כדורגל לבנים - אימונים מקצועיים',
    phone: '050-555-1234',
    email: 'coach@soccerstars.co.il',
    location: 'מגרש הכדורגל העירוני, בית שמש',
    neighborhood: 'בית שמש הותיקה',
    subscriptionTier: 'PREMIUM',
    isVerified: true,
    isActive: true,
    images: [
      { id: 'img-3', url: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800', alt: 'Soccer training', order: 0 },
    ],
  },
  {
    id: 'prov-4',
    userId: 'user-prov-4',
    businessName: 'מוזיקה בשמחה',
    description: 'שיעורי נגינה פרטיים וקבוצתיים - פסנתר, גיטרה, כינור, חליל. מורים מנוסים עם סבלנות לכל גיל. גם הכנה לבחינות בגרות במוזיקה.',
    shortDescription: 'שיעורי נגינה פרטיים - כל הכלים',
    phone: '053-333-4444',
    email: 'music@besimcha.co.il',
    location: 'רחוב הרב קוק 22, רמת בית שמש א׳',
    neighborhood: 'רמת בית שמש א',
    subscriptionTier: 'STANDARD',
    isVerified: true,
    isActive: true,
    images: [
      { id: 'img-4', url: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=800', alt: 'Music lessons', order: 0 },
    ],
  },
  {
    id: 'prov-5',
    userId: 'user-prov-5',
    businessName: 'יצירה וצבע',
    description: 'חוגי אמנות לילדים ומבוגרים. ציור, פיסול, קרמיקה, ויצירה חופשית. סדנאות מיוחדות לימי הולדת ואירועים.',
    shortDescription: 'סטודיו לאמנות - ציור, פיסול, קרמיקה',
    phone: '052-777-8888',
    email: 'art@yetzira.co.il',
    location: 'רחוב דוד המלך 8, רמת בית שמש ג׳',
    neighborhood: 'רמת בית שמש ג',
    subscriptionTier: 'FREE',
    isVerified: false,
    isActive: true,
    images: [
      { id: 'img-5', url: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800', alt: 'Art class', order: 0 },
    ],
  },
  {
    id: 'prov-6',
    userId: 'user-prov-6',
    businessName: 'English Excellence',
    description: 'Private English tutoring for all ages and levels. Specializing in SAT prep, academic writing, and conversational English. Native English speakers.',
    shortDescription: 'שיעורי אנגלית פרטיים - כל הרמות',
    phone: '054-111-2222',
    email: 'learn@englishexcellence.co.il',
    location: 'רחוב האלון 45, רמת בית שמש א׳',
    neighborhood: 'רמת בית שמש א',
    subscriptionTier: 'STANDARD',
    isVerified: true,
    isActive: true,
    images: [
      { id: 'img-6', url: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800', alt: 'English tutoring', order: 0 },
    ],
  },
  {
    id: 'prov-7',
    userId: 'user-prov-7',
    businessName: 'שלום פיצה',
    description: 'פיצריה כשרה למהדרין. פיצות, פסטות, סלטים ומנות ילדים. משלוחים לכל רמת בית שמש.',
    shortDescription: 'פיצריה כשרה למהדרין עם משלוחים',
    phone: '02-991-1234',
    email: 'order@shalompizza.co.il',
    location: 'רחוב נחל דולב 3, רמת בית שמש א׳',
    neighborhood: 'רמת בית שמש א',
    subscriptionTier: 'PREMIUM',
    isVerified: true,
    isActive: true,
    hours: {
      sunday: { open: '11:00', close: '23:00' },
      monday: { open: '11:00', close: '23:00' },
      tuesday: { open: '11:00', close: '23:00' },
      wednesday: { open: '11:00', close: '23:00' },
      thursday: { open: '11:00', close: '23:00' },
      friday: { open: '11:00', close: '14:00' },
    },
    images: [
      { id: 'img-7', url: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800', alt: 'Pizza', order: 0 },
    ],
  },
  {
    id: 'prov-8',
    userId: 'user-prov-8',
    businessName: 'Dr. Sarah Cohen - Therapist',
    description: 'Licensed clinical psychologist specializing in children, adolescents, and families. CBT, play therapy, and parent counseling. English and Hebrew.',
    shortDescription: 'פסיכולוגית קלינית - ילדים ומשפחות',
    phone: '050-999-8765',
    email: 'dr.cohen@therapy.co.il',
    location: 'רחוב הגפן 12, רמת בית שמש ב׳',
    neighborhood: 'רמת בית שמש ב',
    subscriptionTier: 'STANDARD',
    isVerified: true,
    isActive: true,
    images: [
      { id: 'img-8', url: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=800', alt: 'Therapist office', order: 0 },
    ],
  },
  {
    id: 'prov-9',
    userId: 'user-prov-9',
    businessName: 'יוגה בהרים',
    description: 'שיעורי יוגה לנשים בכל הרמות. יוגה בוקר, יוגה ערב, יוגה לאחר לידה. סדנאות מיוחדות ורטריטים.',
    shortDescription: 'שיעורי יוגה לנשים - כל הרמות',
    phone: '054-222-3333',
    email: 'yoga@baharim.co.il',
    location: 'מרכז ספורט רמת בית שמש, רמב״ש ב׳',
    neighborhood: 'רמת בית שמש ב',
    subscriptionTier: 'PREMIUM',
    isVerified: true,
    isActive: true,
    images: [
      { id: 'img-9', url: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800', alt: 'Yoga class', order: 0 },
    ],
  },
  {
    id: 'prov-10',
    userId: 'user-prov-10',
    businessName: 'חשמל מקצועי',
    description: 'חשמלאי מוסמך לכל עבודה - תיקונים, התקנות, שדרוג לוחות חשמל. שירות מהיר ואמין.',
    shortDescription: 'חשמלאי מוסמך - תיקונים והתקנות',
    phone: '052-444-5555',
    email: 'electric@pro.co.il',
    location: 'שירות בכל רמת בית שמש',
    neighborhood: 'רמת בית שמש א',
    subscriptionTier: 'FREE',
    isVerified: true,
    isActive: true,
    images: [
      { id: 'img-10', url: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800', alt: 'Electrician', order: 0 },
    ],
  },
  {
    id: 'prov-11',
    userId: 'user-prov-11',
    businessName: 'צילום שמחות - משה לוי',
    description: 'צלם אירועים מקצועי. חתונות, בר/בת מצווה, בריתות. חבילות צילום סטילס ווידאו. 15 שנות ניסיון.',
    shortDescription: 'צילום אירועים מקצועי - סטילס ווידאו',
    phone: '050-666-7777',
    email: 'moshe@photography.co.il',
    location: 'רחוב הזית 30, רמת בית שמש א׳',
    neighborhood: 'רמת בית שמש א',
    subscriptionTier: 'PREMIUM',
    isVerified: true,
    isActive: true,
    images: [
      { id: 'img-11', url: 'https://images.unsplash.com/photo-1537633552985-df8429e8048b?w=800', alt: 'Event photography', order: 0 },
    ],
  },
  {
    id: 'prov-12',
    userId: 'user-prov-12',
    businessName: 'קייטרינג טעמים',
    description: 'קייטרינג כשר למהדרין לכל אירוע. שבתות חתן, קידושים, בריתות, סעודות מצווה. תפריט מגוון ומחירים הוגנים.',
    shortDescription: 'קייטרינג כשר למהדרין - כל אירוע',
    phone: '02-992-8888',
    email: 'catering@teamim.co.il',
    location: 'אזור תעשייה בית שמש',
    neighborhood: 'בית שמש הותיקה',
    subscriptionTier: 'STANDARD',
    isVerified: true,
    isActive: true,
    images: [
      { id: 'img-12', url: 'https://images.unsplash.com/photo-1555244162-803834f70033?w=800', alt: 'Catering', order: 0 },
    ],
  },
  {
    id: 'prov-13',
    userId: 'user-prov-13',
    businessName: 'Swimming with Rivka',
    description: 'Private and group swimming lessons for girls and women. All ages and levels. Heated pool, patient instruction.',
    shortDescription: 'שיעורי שחייה לבנות ונשים',
    phone: '053-888-9999',
    email: 'rivka@swimming.co.il',
    location: 'בריכת מרכז הספורט, רמב״ש א׳',
    neighborhood: 'רמת בית שמש א',
    subscriptionTier: 'STANDARD',
    isVerified: true,
    isActive: true,
    images: [
      { id: 'img-13', url: 'https://images.unsplash.com/photo-1530549387789-4c1017266635?w=800', alt: 'Swimming lessons', order: 0 },
    ],
  },
  {
    id: 'prov-14',
    userId: 'user-prov-14',
    businessName: 'מתמטיקה קלה',
    description: 'שיעורים פרטיים במתמטיקה לכל הרמות. יסודי, חטיבה, תיכון. הכנה לבגרות 3-5 יחידות. סטודנטית למתמטיקה באוניברסיטה.',
    shortDescription: 'שיעורים פרטיים במתמטיקה - כל הרמות',
    phone: '054-123-7890',
    email: 'math@easy.co.il',
    location: 'רחוב האגוז 18, רמת בית שמש ג׳',
    neighborhood: 'רמת בית שמש ג',
    subscriptionTier: 'FREE',
    isVerified: false,
    isActive: true,
    images: [
      { id: 'img-14', url: 'https://images.unsplash.com/photo-1596495578065-6e0763fa1178?w=800', alt: 'Math tutoring', order: 0 },
    ],
  },
  {
    id: 'prov-15',
    userId: 'user-prov-15',
    businessName: 'הקייטנה של שירה',
    description: 'קייטנת קיץ לילדים גילאי 4-10. פעילויות מגוונות, יצירה, ספורט, טיולים. צוות מסור ומקצועי. ארוחות כשרות.',
    shortDescription: 'קייטנת קיץ לילדים - פעילויות מגוונות',
    phone: '050-321-6543',
    email: 'camp@shira.co.il',
    location: 'בית הספר ממלכתי, רמב״ש א׳',
    neighborhood: 'רמת בית שמש א',
    subscriptionTier: 'PREMIUM',
    isVerified: true,
    isActive: true,
    images: [
      { id: 'img-15', url: 'https://images.unsplash.com/photo-1596464716127-f2a82984de30?w=800', alt: 'Summer camp', order: 0 },
    ],
  },
]

export const getProviderById = (id: string): Provider | undefined => {
  return providers.find((p) => p.id === id)
}

export const getProvidersByTier = (tier: Provider['subscriptionTier']): Provider[] => {
  return providers.filter((p) => p.subscriptionTier === tier)
}

export const getFeaturedProviders = (): Provider[] => {
  return providers.filter((p) => p.subscriptionTier === 'PREMIUM' && p.isVerified)
}

export const getProvidersByNeighborhood = (neighborhood: string): Provider[] => {
  return providers.filter((p) => p.neighborhood === neighborhood)
}
